Repository boostcamp-2020/Project08-A-Styled-Map-Admin-Tool, pull requests merged in 2020-12, with the labels that each got.

#88 지도의 스타일을 변경 가능한 util함수 및 각 feature별로 변경을 위한 함수 작성
  public/images/logo.png
  public/images/map.png
  src/components/Canvas.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/hooks/sidebar/useStyleType.ts
  src/hooks/useCanvas.ts
  src/pages/Entry.tsx
  src/store/map/initializeMap.ts
  src/store/map/layers/mapbox-poi.ts
  src/store/style/compareStyle.ts
  src/store/style/properties.ts
  src/utils/applyStyle.ts
  src/utils/colorFormat.ts
  src/utils/map-styling/administrative.ts
  src/utils/map-styling/index.ts
  src/utils/map-styling/landscape.ts
  src/utils/map-styling/marker.ts
  src/utils/map-styling/poi.ts
  src/utils/map-styling/road.ts
  src/utils/map-styling/transit.ts
  src/utils/map-styling/water.ts
  src/utils/styles/styled.ts
Labels: must, review, 스타일 유형

#89 서울 샘플데이터 분류 및 레이어 추가
  src/store/map/initializeMap.ts
  src/store/map/layers/landscape.ts
  src/store/map/layers/poi.ts
  src/store/map/layers/road.ts
  src/store/map/layers/transit.ts
  src/store/map/layers/water.ts
Labels: must, 스타일 유형

#91 전날 리뷰를 토대로 리팩토링
  .eslintrc
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStyle.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/components/Sidebar/SidebarContentMore/WeightStyle.tsx
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/map/initializeMap.ts
  src/store/map/layers/landscape.ts
  src/store/map/layers/poi.ts
  src/store/map/layers/transit.ts
  src/store/map/layers/water.ts
  src/store/style/compareStyle.ts
  src/store/style/getReducer.ts
  src/store/style/properties.ts
Labels: 스타일 유형, 지도

#94 도로 항목 스타일 적용
  src/hooks/sidebar/useStyleType.ts
  src/store/map/layers/road.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/index.ts
  src/utils/map-styling/road.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must, 스타일 유형

#92 스타일 조정 공통함수 일부 수정. 물, 행정구역 스타일 설정 함수 구현
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStyle.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/components/Sidebar/SidebarContentMore/WeightStyle.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/map/layers/water.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/administrative.ts
  src/utils/map-styling/index.ts
  src/utils/map-styling/water.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must, 스타일 유형

#93 지도에서 poi의 스타일을 수정하는 함수 구현
  src/store/map/layers/mapbox-poi.ts
  src/store/map/layers/poi.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/poi.ts
  src/utils/rendering-data/layersColor.ts
  src/utils/rendering-data/layersColor2.ts
Labels: must, review, 스타일 유형

#97 각 카테고리에 따른 지도 스타일 적용 병합
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStyle.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/components/Sidebar/SidebarContentMore/WeightStyle.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/style/compareStyle.ts
  src/store/style/getReducer.ts
  src/store/style/properties.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/administrative.ts
  src/utils/map-styling/index.ts
  src/utils/map-styling/landscape.ts
  src/utils/map-styling/poi.ts
  src/utils/map-styling/road.ts
  src/utils/map-styling/transit.ts
  src/utils/map-styling/water.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must, 스타일 유형

#99 [공사중] 초기에 defaultColor를 주기 위해서 타입을 지정중이다
  src/store/common/type.ts
  src/store/style/getReducer.ts
  src/store/style/properties.ts
  src/utils/rendering-data/layerColor3.ts
  src/utils/rendering-data/layersColor.ts
  src/utils/rendering-data/layersColor2.ts
Labels: bug

#98 레이어에 없는 속성 조정 시 발생했던 에러 해결 및 일부 기본 색상 수정
  src/store/map/layers/transit.ts
  src/utils/map-styling/transit.ts
Labels: enhancement, must, 스타일 유형

#100 도로 레이어 분리 및 재조립 / 스타일 적용 / 리팩토링
  src/store/map/initializeMap.ts
  src/store/map/layers/road.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/local.ts
  src/utils/map-styling/road-categories/sidewalk.ts
  src/utils/map-styling/road-categories/stylingCategory.ts
  src/utils/map-styling/road.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must, 스타일 유형

#104 Landscape 부문의 기존 street 테마 속성 변환 기능 구현
  src/store/map/initializeMap.ts
  src/utils/map-styling/landscape.ts
Labels: must, 레이아웃

#101 초기에 상태 설정 할 때 색상이 각 feature/detail마다 설정되도록 함
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/map/initializeMap.ts
  src/store/style/compareStyle.ts
  src/store/style/getReducer.ts
  src/store/style/properties.ts
  src/utils/applyStyle.ts
  src/utils/colorFormat.ts
  src/utils/map-styling/poi.ts
  src/utils/rendering-data/layerColor3.ts
  src/utils/rendering-data/layersColor.ts
  src/utils/rendering-data/layersColor2.ts
  src/utils/rendering-data/layersColor4.ts
Labels: review, 스타일 유형

#105 충돌이슈제거, 버그 픽스, 리팩토링
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/map/initializeMap.ts
  src/store/map/layers/transit.ts
  src/store/style/compareStyle.ts
  src/store/style/getReducer.ts
  src/store/style/properties.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/administrative.ts
  src/utils/map-styling/index.ts
  src/utils/map-styling/landscape.ts
  src/utils/map-styling/marker.ts
  src/utils/map-styling/poi.ts
  src/utils/map-styling/road-categories/all.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/local.ts
  src/utils/map-styling/road-categories/sidewalk.ts
  src/utils/map-styling/road-categories/stylingCategory.ts
  src/utils/map-styling/road.ts
  src/utils/map-styling/transit.ts
  src/utils/map-styling/water.ts
  src/utils/rendering-data/initLayerColor.ts
  src/utils/rendering-data/layersColor.ts
  src/utils/rendering-data/layersColor2.ts
  src/utils/rendering-data/layersColor4.ts
Labels: must, 스타일 유형

#109 전체 스타일 변경 액션 추가
  src/components/Sidebar/SidebarModal/ImportModal.tsx
  src/hooks/common/useWholeStyle.ts
  src/store/common/type.ts
  src/store/style/action.ts
  src/store/style/getReducer.ts
  src/store/style/manageCategories.ts
Labels: help wanted, must, 스타일 유형

#111 현재 선택한 사이드바의 항목을 상태로 분리
  package-lock.json
  package.json
  src/App.tsx
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypeItem.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/hooks/sidebar/useSidebarType.ts
  src/hooks/sidebar/useStyleType.ts
  src/index.tsx
  src/pages/Entry.tsx
  src/store/common/type.ts
  src/store/sidebar/action.ts
  src/store/sidebar/reducer.ts
  src/store/style/getReducer.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: review

#112 DetailType.tsx 리팩토링
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypeSubList.tsx
Labels: help wanted, question, review

#118 URL <> JSON 파싱 함수 구현 및 poi 스타일링 버그 수정
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/map/layers/poi.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/sidewalk.ts
  src/utils/rendering-data/initLayerColor.ts
  src/utils/rendering-data/theme/blueprint.json
  src/utils/urlParsing.ts
  src/utils/urlTest.json
Labels: must, 가져오기, 내보내기

#119 [리뷰요청] 전체 스타일 변경 - input Validation, 전체 맵 스타일링 함수, 변경상태 추가
  src/components/Sidebar/SidebarModal/ImportModal.tsx
  src/hooks/common/useModalStatus.ts
  src/hooks/common/useWholeStyle.ts
  src/hooks/sidebar/useImportModalStatus.ts
  src/hooks/sidebar/useSidebarDropdown.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/style/compareStyle.ts
  src/store/style/getReducer.ts
  src/store/style/manageCategories.ts
  src/utils/setFeatureStyle.ts
  src/utils/styles/styled.ts
  src/utils/validateStyle.ts
Labels: must, review, 가져오기

#121 Export style 구현
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypeSubList.tsx
  src/components/Sidebar/SidebarFooter/SidebarFooter.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/components/Sidebar/SidebarModal/ImportModal.tsx
  src/components/Sidebar/SidebarModal/common.tsx
  src/hooks/sidebar/useExportStyle.ts
  src/hooks/sidebar/useSidebarFooter.ts
  src/utils/map-styling/landscape.ts
Labels: 내보내기

#129 가시성 체크 함수 에러 픽스
  src/store/common/type.ts
  src/utils/validateStyle.ts
Labels: must, 가져오기

#120 로그를 볼 수 있는 기능 추가
  src/components/Icon/RedoIcon.tsx
  src/components/Map/ButtonGroup/Button.tsx
  src/components/Map/ButtonGroup/UpperButtons.tsx
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeader.tsx
  src/hooks/map/useHistoryFeature.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/history/action.ts
  src/store/history/reducer.ts
  src/store/index.ts
  src/utils/getRandomId.ts
  src/utils/map-styling/road-categories/all.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/stylingCategory.ts
  src/utils/rendering-data/layersColor.ts
Labels: must

#131 [fix] 조건문 통합 에러 수정
  src/utils/validateStyle.ts
Labels: must, 가져오기

#122 비교하기 기능 기본 레이아웃 구현 및 색상 속성 동시 변경 기능 구현
  .gitmessage
  package-lock.json
  package.json
  public/index.html
  src/components/Icon/RemoveIcon.tsx
  src/components/Map/ButtonGroup/Button.tsx
  src/components/Map/ButtonGroup/LowerButtons.tsx
  src/components/Map/ButtonGroup/UpperButtons.tsx
  src/components/Map/Map.tsx
  src/components/Map/SearchInput/SearchInput.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarContentMore/ColorStyle2.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/hooks/map/getCompareMap.js
  src/hooks/map/useComparisonButton.ts
  src/hooks/map/useUpperButtons.ts
  src/hooks/sidebar/useStyleType.ts
Labels: help wanted, must

#132 History & Compare 기능 merge에 따른 오류 수정
  src/components/Map/ButtonGroup/UpperButtons.tsx
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
Labels: must, 비교하기, 히스토리

#133 all에 대한 export 처리 / export 시 길어지는 json 에 대한 overflow 처리
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/hooks/sidebar/useExportStyle.ts
Labels: must

#134 히스토리 전체 상태 localStorage 저장 추가
  src/components/Map/History/History.tsx
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/hooks/map/useHistoryFeature.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/history/action.ts
  src/store/history/reducer.ts
  src/utils/urlParsing.ts
Labels: must, 히스토리

#135 parsing된 url로 지도 스타일링 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Map/Map.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/hooks/map/useMap.ts
  src/pages/Main.tsx
  src/store/map/action.ts
  src/store/map/initializeMap.ts
  src/store/map/reducer.ts
  src/utils/applyStyle.ts
  src/utils/urlParsing.ts
Labels: could, 내보내기

#137 비교하기 기능 관련 Hook 및 컴포넌트 수정
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/hooks/map/useCompareFeature.ts
  src/hooks/map/useComparisonButton.ts
  src/hooks/map/useMap.ts
  src/hooks/map/useUpperButtons.ts
  src/store/map/initializeMap.ts
Labels: could, 비교하기

#138 show페이지 이동 시 url파싱 후 스타일 적용 문제 해결
  src/components/Map/Map.tsx
  src/hooks/common/useWholeStyle.ts
  src/hooks/map/useMap.ts
  src/pages/Main.tsx
  src/utils/urlParsing.ts
  src/utils/validateStyle.ts
Labels: must, review, 가져오기

#141 [재요청] input 스타일 검증 함수 에러 픽스
  src/utils/validateStyle.ts
Labels: bux fix

#139 명도 / 채도 변경 시 input color의 색 변경 오류 수정
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStyle.tsx
  src/store/map/initializeMap.ts
  src/utils/applyStyle.ts
  src/utils/colorFormat.ts
Labels: bux fix, must

#144 새로고침 후 마지막 지도 스타일 유지 / undo, redo 구현
  src/components/Icon/RedoIcon.tsx
  src/components/Icon/UndoIcon.tsx
  src/components/Map/History/History.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypeSubList.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeader.tsx
  src/hooks/common/useWholeStyle.ts
  src/hooks/map/useMap.ts
  src/hooks/sidebar/useSidebarFooter.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useUndoRedo.ts
  src/store/common/type.ts
  src/store/history/action.ts
  src/store/history/reducer.ts
  src/store/style/action.ts
  src/store/style/getReducer.ts
Labels: must

#143 로그를 이용한 비교하기 구현
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/components/Sidebar/SidebarContentFewer/ThemeItem.tsx
  src/components/Sidebar/SidebarFooter/SidebarFooter.tsx
  src/components/Sidebar/SidebarHeader/SidebarDropdown.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/components/Sidebar/SidebarModal/ImportModal.tsx
  src/components/common/Overlay.tsx
  src/hooks/map/getCompareMap.js
  src/hooks/map/useCompareFeature.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useTheme.ts
  src/pages/Main.tsx
  src/store/common/type.ts
  src/store/history/reducer.ts
  src/utils/rendering-data/layers/poi.json
  src/utils/rendering-data/sidebarThemeData.ts
Labels: 비교하기, 히스토리

#153 #148 에서 문제있었던 layer filter 오류 수정
  src/utils/map-styling/transit.ts
Labels: bug fix

#156 기본값 설정을 위한 통합과정에서의 bug fix / 가시성 부모 요소 상속 추가
  src/components/Sidebar/SidebarContentMore/DetailTypeSubList.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/hooks/map/useCompareFeature.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/map/initializeMap.ts
  src/store/map/layers/landscape.ts
  src/store/map/layers/mapbox-poi.ts
  src/store/map/layers/poi.ts
  src/store/map/layers/road.ts
  src/store/map/layers/transit.ts
  src/store/map/layers/water.ts
  src/store/style/properties.ts
  src/utils/map-styling/administrative.ts
  src/utils/map-styling/landscape.ts
  src/utils/map-styling/landscape2.ts
  src/utils/map-styling/landscape3.ts
  src/utils/map-styling/road-categories/local.ts
  src/utils/map-styling/transit.ts
  src/utils/map-styling/water.ts
  src/utils/rendering-data/defaultStyle.ts
  src/utils/rendering-data/initLayerColor.ts
  src/utils/rendering-data/layers/administrative.json
  src/utils/rendering-data/layers/init.ts
  src/utils/rendering-data/layers/landscape.ts
  src/utils/rendering-data/layers/poi.json
  src/utils/rendering-data/layers/road.json
  src/utils/rendering-data/layers/transit.json
  src/utils/rendering-data/layers/water.json
  src/utils/rendering-data/layersColor.ts
  src/utils/validateStyle.ts
Labels: must

#157 현재, 비교 중인 로그 히스토리에서 표기, 리팩토링
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypeItem.tsx
  src/hooks/common/useWholeStyle.ts
  src/hooks/map/useCompareFeature.ts
  src/hooks/map/useLowerButtons.ts
  src/hooks/sidebar/useExportStyle.ts
  src/hooks/sidebar/useSidebarFooter.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useUndoRedo.ts
  src/store/common/type.ts
Labels: could, 히스토리

#158 초기화 및 도로 레이어들을 쪼갬
  src/hooks/sidebar/useSidebarDropdown.ts
  src/utils/map-styling/road-categories/all.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/highway.ts
  src/utils/map-styling/road-categories/stylingCategory.ts
  src/utils/map-styling/road.ts
  src/utils/rendering-data/defaultStyle.ts
  src/utils/rendering-data/featureTypeData.ts
  src/utils/rendering-data/layers/administrative.json
  src/utils/rendering-data/layers/init.ts
  src/utils/rendering-data/layers/landscape.ts
  src/utils/rendering-data/layers/poi.json
  src/utils/rendering-data/layers/road.json
  src/utils/rendering-data/layers/transit.json
  src/utils/rendering-data/layers/weightTemplate.ts
  src/utils/rendering-data/theme/blueprint.json
Labels: must

#159 도로 및 행정구역 표기단계 조절 위한 hooks 구현, 교통 styler 함수 리팩토링
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContentFewer/DepthItem.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContent.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContentDepth.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContentTheme.tsx
  src/hooks/sidebar/useSidebarDepthItem.ts
  src/utils/applyStyle.ts
  src/utils/map-styling/transit.ts
  src/utils/rendering-data/layers/transit.json
Labels: bug fix, must

#165 마커 리듀서, 마커 추가 및 초기화 기능 구현
  src/components/Icon/CloseIcon.tsx
  src/components/Map/Map.tsx
  src/components/Map/Marker/MarkerPopup.tsx
  src/hooks/common/useWholeStyle.ts
  src/hooks/map/useHistoryFeature.ts
  src/hooks/map/useMap.ts
  src/hooks/map/useMarkerFeature.ts
  src/hooks/map/useMarkerPopUp.ts
  src/store/common/type.ts
  src/store/index.ts
  src/store/marker/action.ts
  src/store/marker/reducer.ts
  src/store/style/reducer.ts
  src/utils/map-styling/landscape3.ts
  src/utils/rendering-data/defaultStyle.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: could, review

#164 원래 색상으로 돌아갈 수 있는 색상 초기화 기능 추가 및 url파싱 시 좌표도 같이 파싱
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/map/useMap.ts
  src/hooks/sidebar/useExportStyle.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useUndoRedo.ts
  src/store/common/type.ts
  src/store/map/action.ts
  src/store/map/initializeMap.ts
  src/store/style/action.ts
  src/store/style/getReducer.ts
  src/store/style/properties.ts
  src/utils/colorFormat.ts
  src/utils/removeNullFromObject.ts
  src/utils/rendering-data/layers/administrative.json
  src/utils/rendering-data/layers/init.ts
  src/utils/rendering-data/layers/road.json
  src/utils/rendering-data/layers/transit.json
  src/utils/urlParsing.ts
Labels: bug fix, must, review

#170 도로 색 변경후 새로고침 후 생기는 이슈 해결
  src/components/common/Overlay.tsx
  src/hooks/common/useWholeStyle.ts
  src/hooks/sidebar/useStyleType.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/local.ts
  src/utils/map-styling/road-categories/stylingCategory.ts
  src/utils/rendering-data/layers/init.ts
  src/utils/rendering-data/layers/weightTemplate.ts
  src/utils/rendering-data/theme/blueprint.json
Labels: bug fix

#174 간단한 리팩토링 사항 처리
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/components/Map/Marker/MarkerPopup.tsx
  src/components/Sidebar/SidebarContentFewer/DepthItem.tsx
  src/hooks/map/useCompareFeature.ts
  src/hooks/map/useMap.ts
  src/hooks/map/useMapTheme.ts
  src/hooks/map/useMarkerFeature.ts
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/hooks/sidebar/useSidebarDepthItem.ts
  src/hooks/sidebar/useSidebarType.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useUndoRedo.ts
  src/store/common/type.ts
  src/store/depth-theme/action.ts
  src/store/depth-theme/reducer.ts
  src/store/history/reducer.ts
  src/store/map/reducer.ts
  src/store/marker/action.ts
  src/store/marker/reducer.ts
  src/store/sidebar/action.ts
  src/store/sidebar/reducer.ts
  src/utils/getTypeName.ts
Labels: bug fix, refactor

#175 marker 우클릭 삭제기능 추가 / marker 수 제한 추가 / marker bug fix
  src/components/Map/Marker/MarkerPopup.tsx
  src/hooks/map/useMarkerFeature.ts
  src/store/marker/reducer.ts
Labels: bug fix, marker

#176 Styling파일들 리팩토링 및 any제거
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/hooks/map/useMap.ts
  src/hooks/map/useMarkerFeature.ts
  src/hooks/sidebar/useExportStyle.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/depth-theme/reducer.ts
  src/store/style/properties.ts
  src/utils/applyStyle.ts
  src/utils/colorFormat.ts
  src/utils/map-styling/administrative.ts
  src/utils/map-styling/index.ts
  src/utils/map-styling/landscape.ts
  src/utils/map-styling/macgyver/mappingDetailToFunc.ts
  src/utils/map-styling/macgyver/seperatedLayers.ts
  src/utils/map-styling/macgyver/utils.ts
  src/utils/map-styling/macgyver/weightTemplate.ts
  src/utils/map-styling/marker.ts
  src/utils/map-styling/poi.ts
  src/utils/map-styling/road-categories/all.ts
  src/utils/map-styling/road-categories/arterial.ts
  src/utils/map-styling/road-categories/highway.ts
  src/utils/map-styling/road-categories/local.ts
  src/utils/map-styling/road-categories/sidewalk.ts
  src/utils/map-styling/road-categories/stylingCategory.ts
  src/utils/map-styling/road.ts
  src/utils/map-styling/transit.ts
  src/utils/map-styling/water.ts
  src/utils/removeNullFromObject.ts
  src/utils/rendering-data/defaultStyle.ts
  src/utils/rendering-data/layers/administrative.json
  src/utils/rendering-data/layers/init.ts
  src/utils/rendering-data/layers/landscape.ts
  src/utils/rendering-data/layers/road.json
  src/utils/rendering-data/layers/water.json
  src/utils/urlParsing.ts
  src/utils/urlTest.json
Labels: refactor, review

#178 검색기능 추가 / export 창의 copy 기능 추가
  package-lock.json
  package.json
  src/components/Icon/Copy.tsx
  src/components/Map/ButtonGroup/UpperButtons.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/hooks/map/useMarkerFeature.ts
  src/hooks/sidebar/useCopyToClipboard.ts
  src/store/map/geocoder.d.ts
  src/store/map/initializeMap.ts
  src/utils/rendering-data/sidebarThemeData.ts
  src/utils/rendering-data/theme/dark.json
Labels: could, 검색기능

#183 [재요청] 히스토리 전체 수정 관련 로그, Unod/Redo 기능 추가, 표기단계 조절 에러 픽스 & 리팩토링
  src/components/Map/History/History.tsx
  src/components/Map/History/ReplaceHistoryContent.tsx
  src/components/Map/History/SetHistoryContent.tsx
  src/components/Sidebar/SidebarContentFewer/ThemeItem.tsx
  src/hooks/common/useWholeStyle.ts
  src/hooks/map/useMapTheme.ts
  src/hooks/sidebar/useImportModalStatus.ts
  src/hooks/sidebar/useSidebarDepthItem.ts
  src/hooks/sidebar/useSidebarDropdown.ts
  src/hooks/sidebar/useTheme.ts
  src/hooks/sidebar/useUndoRedo.ts
  src/store/common/type.ts
  src/store/depth-theme/action.ts
  src/store/depth-theme/reducer.ts
  src/store/marker/action.ts
  src/store/style/action.ts
  src/store/style/getReducer.ts
  src/store/style/manageCategories.ts
  src/utils/getTypeName.ts
  src/utils/rendering-data/sidebarThemeData.ts
  src/utils/rendering-data/theme/christmas.json
Labels: bug fix, refactor

#180 마커 내보내기 (URL/JSON) 기능 구현 및 가져오기 (URL) 함수 추가
  src/App.tsx
  src/components/Map/Map.tsx
  src/components/Sidebar/SidebarModal/ExportModal.tsx
  src/hooks/map/useMap.ts
  src/hooks/map/useMarkerFeature.ts
  src/hooks/sidebar/useExportStyle.ts
  src/hooks/sidebar/useSidebarFooter.ts
  src/pages/Main.tsx
  src/store/common/type.ts
  src/store/map/initializeMap.ts
  src/store/map/reducer.ts
  src/store/marker/action.ts
  src/store/marker/reducer.ts
  src/utils/map-styling/marker.ts
  src/utils/urlParsing.ts
Labels: bug, 가져오기, 내보내기

#185 Merge 이후 발견한 에러, 빠진 부분 픽스
  src/components/Map/History/ReplaceHistoryContent.tsx
  src/hooks/sidebar/useUndoRedo.ts
  src/utils/getTypeName.ts
  src/utils/map-styling/marker.ts
  src/utils/rendering-data/defaultStyle.ts
  src/utils/rendering-data/layers/init.ts
Labels: bug fix

#186 dark 테마 수정 / history reset 추가
  src/components/Map/History/History.tsx
  src/store/common/type.ts
  src/store/history/action.ts
  src/store/history/reducer.ts
  src/utils/rendering-data/sidebarThemeData.ts
  src/utils/rendering-data/theme/dark.json
Labels: could

#187 스케치 테마 추가 및 merge 이후 에러 수정
  src/hooks/sidebar/useExportStyle.ts
  src/utils/rendering-data/sidebarThemeData.ts
  src/utils/rendering-data/theme/sketch.json
Labels: bug fix, 내보내기

#192 history reset bug fix
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/components/Sidebar/SidebarContentMore/ColorStyle2.tsx
  src/hooks/map/useCompareFeature.ts
  src/hooks/map/useHistoryFeature.ts
  src/hooks/sidebar/useCopyToClipboard.ts
  src/hooks/sidebar/useStyleType.ts
Labels: bug fix

#194 url 파싱의 숫자 변환 추가
  src/hooks/map/useMap.ts
  src/utils/urlParsing.ts
Labels: bug fix

#201 color saturation lightness API 호출방식 refactoring
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStyle.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/components/Sidebar/SidebarContentMore/WeightStyle.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useUndoRedo.ts
  src/store/common/type.ts
  src/store/style/properties.ts
  src/utils/applyStyle.ts
  src/utils/getTypeName.ts
  src/utils/setFeatureStyle.ts
  src/utils/styles/globalStyle.tsx
  src/utils/validateStyle.ts
Labels: refactor, 스타일 유형

#203 validate 에러 픽스, filter expression 간소화
  src/utils/rendering-data/layers/init.ts
  src/utils/validateStyle.ts
Labels: bug fix

#204 불필요한 useEffect 실행 관련 리팩토링
  src/components/Map/History/History.tsx
  src/components/Map/Map.tsx
  src/components/Map/Marker/MarkerPopup.tsx
  src/hooks/map/useCompareFeature.ts
  src/hooks/map/useHistoryFeature.ts
  src/hooks/map/useHistoryMap.ts
  src/hooks/map/useMap.ts
  src/hooks/map/useMarkerFeature.ts
  src/hooks/sidebar/useStyleType.ts
  src/pages/Main.tsx
  src/store/history/reducer.ts
  src/store/map/initializeMap.ts
  src/utils/rendering-data/defaultStyle.ts
  src/utils/rendering-data/theme/christmas.json
  src/utils/rendering-data/theme/monochrome.json
  src/utils/updateMarkerStorage.ts
Labels: bug fix, refactor

#206 localStorage 저장 갯수 제한 및 간단한 버그 픽스
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/map/useHistoryMap.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/style/getReducer.ts
  src/utils/colorFormat.ts
  src/utils/setFeatureStyle.ts
Labels: bug fix

#208 초기화 버튼 클릭시 - 기본 사이드바도 초기화 되도록 수정
  src/components/Map/Map.tsx
  src/components/Map/Marker/MarkerPopup.tsx
  src/hooks/map/useMarkerPopUp.ts
  src/hooks/map/useMarkerPosition.ts
  src/hooks/map/useMarkerRegister.ts
  src/hooks/sidebar/useSidebarDropdown.ts
  src/utils/validateStyle.ts
Labels: refactor

#209 Undo/Redo 전체 색상 초기화 처리
  src/hooks/sidebar/useInitAllColor.ts
  src/hooks/sidebar/useStyleType.ts
  src/hooks/sidebar/useUndoRedo.ts
Labels: bug fix, refactor

#221 가져오기 마커 import 조건문 수정
  src/hooks/sidebar/useImportModalStatus.ts
Labels: bug fix
