Repository boostcamp-2020/Project08-A-Styled-Map-Admin-Tool, pull requests merged in 2020-11, with the labels that each got.

#11 사이드바의 상세 테마 설정 UI 구현
  public/icon.svg
  public/index.html
  src/components/Sidebar/SidebarContent/SidebarContentPresenter.tsx
  src/components/Sidebar/SidebarContent/SidebarContentThemeContainer.tsx
  src/components/Sidebar/SidebarContent/SidebarContentThemePresenter.tsx
  src/components/Sidebar/SidebarPresenter.tsx
  src/utils/styles/globalStyle.tsx
Labels: must, 레이아웃

#12 기본 사이드바 - 표기 단계 조절 컴포넌트
  src/components/Icon/UndoIcon.tsx
  src/components/Sidebar/SidebarContent/DepthItemPresenter.tsx
  src/components/Sidebar/SidebarContent/SidebarContentPresenter.tsx
  src/components/Sidebar/SidebarPresenter.tsx
Labels: must, 레이아웃

#13 사이드바 병합 후 스타일 수정
  src/components/Sidebar/SidebarContent/DepthItemPresenter.tsx
  src/components/Sidebar/SidebarContent/SidebarContentPresenter.tsx
  src/components/Sidebar/SidebarContent/SidebarContentThemePresenter.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeaderPresenter.tsx
Labels: must, 레이아웃

#16 지도 우측 컴포넌트(검색창 및 버튼들) 추가 및 리뷰에 따른 리팩토링
  src/components/Map/Button/ButtonPresenter.tsx
  src/components/Map/ButtonGroup/UpperButtons/UpperButtonsContainer.tsx
  src/components/Map/ButtonGroup/UpperButtons/UpperButtonsPresenter.tsx
  src/components/Map/MapContainer.tsx
  src/components/Map/MapPresenter.tsx
  src/components/Map/SearchInput/SearchInputContainer.tsx
  src/components/Map/SearchInput/SearchInputPresenter.tsx
Labels: must, 레이아웃

#17 좌측 사이드바 More options 레이아웃 및 토글 구현
  src/components/Sidebar/SidebarContentFewer/DepthItemPresenter.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypePresenter.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypePresenter.tsx
  src/components/Sidebar/SidebarContentMore/SidebarContentContainer.tsx
  src/components/Sidebar/SidebarContentMore/SidebarContentPresenter.tsx
  src/components/Sidebar/SidebarContentMore/StylerPresenter.tsx
  src/utils/styles/styled.ts
Labels: must, 레이아웃

#18 1주차 구현내용 전반적으로 리팩토링 진행
  README.md
  src/components/Map/Button/ButtonPresenter.tsx
  src/components/Map/ButtonGroup/UpperButtonsContainer.tsx
  src/components/Map/ButtonGroup/UpperButtonsPresenter.tsx
  src/components/Map/MapPresenter.tsx
  src/components/Map/SearchInput/SearchInputPresenter.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContentThemePresenter.tsx
  src/components/Sidebar/SidebarContentFewer/ThemeItemPresenter.tsx
  src/components/Sidebar/SidebarContentMore/ColorStylePresenter.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypeContainer.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypePresenter.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypePresenter.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyleWrapper.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStylePresenter.tsx
  src/components/Sidebar/SidebarContentMore/SidebarContentContainer.tsx
  src/components/Sidebar/SidebarContentMore/StylerPresenter.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStylePresenter.tsx
  src/components/Sidebar/SidebarContentMore/WeightStylePresenter.tsx
  src/components/Sidebar/SidebarFooter/SidebarFooterPresenter.tsx
  src/utils/redering-data/featureTypeData.ts
  src/utils/redering-data/sidebarThemeData.ts
Labels: must, 레이아웃

#19 메인 화면 CSS 스타일 조정
  src/components/Map/Button/ButtonPresenter.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypePresenter.tsx
  src/components/Sidebar/SidebarFooter/SidebarFooterPresenter.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeaderPresenter.tsx
Labels: 레이아웃

#20 전반적인 레이아웃 조절
  src/components/Icon/Compare.tsx
  src/components/Icon/FullScreen.tsx
  src/components/Icon/SmallScreen.tsx
  src/components/Map/Button/ButtonPresenter.tsx
  src/components/Map/ButtonGroup/UpperButtonsPresenter.tsx
  src/components/Map/SearchInput/SearchInputPresenter.tsx
  src/components/Sidebar/SidebarContentFewer/DepthItemPresenter.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContentDepthPresenter.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContentPresenter.tsx
  src/components/Sidebar/SidebarContentFewer/SidebarContentThemePresenter.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypePresenter.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyleWrapper.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStylePresenter.tsx
  src/components/Sidebar/SidebarContentMore/StylerPresenter.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStylePresenter.tsx
  src/components/Sidebar/SidebarContentMore/WeightStylePresenter.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeaderPresenter.tsx
Labels: 레이아웃

#39 사이드바 헤더 드롭다운 & Import 모달 창 구현
  src/components/Icon/CloseIcon.tsx
  src/components/Icon/MoreVertIcon.tsx
  src/components/Sidebar/SidebarHeader/SidebarDropdownContainer.tsx
  src/components/Sidebar/SidebarHeader/SidebarDropdownPresenter.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeaderContainer.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeaderPresenter.tsx
  src/components/Sidebar/SidebarModal/ImportModalContainer.tsx
  src/components/Sidebar/SidebarModal/ImportModalPresenter.tsx
  src/utils/styles/styled.ts
Labels: must, 레이아웃

#38 우측 상/하단 버튼들 컴포넌트 생성 및 기능 구현
  src/components/Icon/AddIcon.tsx
  src/components/Icon/FullScreen.tsx
  src/components/Icon/RemoveIcon.tsx
  src/components/Icon/SmallScreen.tsx
  src/components/Map/Button/ButtonPresenter.tsx
  src/components/Map/ButtonGroup/LowerButtonsContainer.tsx
  src/components/Map/ButtonGroup/LowerButtonsPresenter.tsx
  src/components/Map/ButtonGroup/UpperButtonsContainer.tsx
  src/components/Map/ButtonGroup/UpperButtonsPresenter.tsx
  src/components/Map/MapContainer.tsx
  src/components/Map/MapPresenter.tsx
Labels: must, 레이아웃

#42 Hooks 관련 리팩토링
  src/components/Map/Map.tsx
  src/components/Map/SearchInput/SearchInput.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarModal/ImportModal.tsx
  src/hooks/useInputText.ts
  src/hooks/useModalStatus.ts
  src/hooks/useSidebar.ts
  src/hooks/useSidebarImportModal.ts
  src/hooks/useToggleStatus.ts
Labels: 레이아웃

#47 기능 유형 수정 사항 반영
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarContentMore/SidebarContent.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/components/Sidebar/SidebarHeader/SidebarHeader.tsx
  src/utils/redering-data/featureTypeData.ts
Labels: 레이아웃

#48 poi관련 상태 생성 및 기능/세부 유형 리스트에 상태 변경여부 표기
  src/components/Sidebar/SidebarContentFewer/SidebarContentTheme.tsx
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypeItem.tsx
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/hooks/sidebar/useSidebarType.ts
  src/store/common/action.ts
  src/store/common/commonProperties.ts
  src/store/index.ts
  src/store/map/action.ts
  src/store/style/poiReducer.ts
  src/utils/redering-data/featureTypeData.ts
  src/utils/rendering-data/featureTypeData.ts
  src/utils/rendering-data/sidebarThemeData.ts
Labels: review, 기능유형

#49 경관 메뉴 및 세부 메뉴 클릭에 따른 reducer 추가
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/store/index.ts
  src/store/style/landscapeReducer.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must

#50 행정구역 reducer 추가
  src/store/index.ts
  src/store/style/administrativeReducer.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must

#53 water / marker에 대한 리듀서 추가 및 타입 수정
  src/components/Sidebar/SidebarContentMore/FeatureTypeItem.tsx
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/store/index.ts
  src/store/style/markerReducer.ts
  src/store/style/waterReducer.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: 기능유형

#54 리덕스 상태 관련 함수 병합
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypeItem.tsx
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/store/common/action.ts
  src/store/common/properties.ts
  src/store/common/reducer.ts
  src/store/common/type.ts
  src/store/index.ts
  src/store/style/administrativeReducer.ts
  src/store/style/landscapeReducer.ts
  src/store/style/markerReducer.ts
  src/store/style/poiReducer.ts
  src/store/style/roadReducer.ts
  src/store/style/transitReducer.ts
  src/store/style/waterReducer.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: must

#55 github action배포 파일 추가
  .github/workflows/deploy.yml
Labels: could

#61 Redux Reduce, Action 리팩토링, 공통 타입 분류, 스타일 전역 상태 조회 Hook 구현
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/DetailTypeItem.tsx
  src/components/Sidebar/SidebarContentMore/FeatureType.tsx
  src/components/Sidebar/SidebarContentMore/FeatureTypeItem.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useFeatureTypeItem.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/action.ts
  src/store/common/properties.ts
  src/store/common/reducer.ts
  src/store/common/type.ts
  src/store/style/markerReducer.ts
  src/store/style/waterReducer.ts
  src/utils/rendering-data/featureTypeData.ts
Labels: help wanted, 기능유형

#62 기존 코드에서 부족한 부분 리팩토링 & 스타일 상태변경 구현
  package-lock.json
  package.json
  src/components/Sidebar/SidebarContentMore/ColorStyle.tsx
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/components/Sidebar/SidebarContentMore/LightnessStyle.tsx
  src/components/Sidebar/SidebarContentMore/SaturationStyle.tsx
  src/components/Sidebar/SidebarContentMore/Styler.tsx
  src/components/Sidebar/SidebarContentMore/VisibilityStyle.tsx
  src/components/Sidebar/SidebarContentMore/WeightStyle.tsx
  src/hooks/common/useInputRange.ts
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/action.ts
  src/store/common/properties.ts
  src/store/common/reducer.ts
  src/store/common/type.ts
  src/store/index.ts
  src/store/map/initializeMap.ts
  src/store/style/markerReducer.ts
  src/store/style/waterReducer.ts
  src/utils/typeCheck.ts
Labels: review, 기능유형

#87 스타일 변경 상태 추가, water/marker 상태 구조 통일시킴
  src/components/Sidebar/SidebarContentMore/DetailType.tsx
  src/hooks/sidebar/useDetailType.ts
  src/hooks/sidebar/useStyleType.ts
  src/store/common/type.ts
  src/store/index.ts
  src/store/style/action.ts
  src/store/style/administrativeReducer.ts
  src/store/style/compareStyle.ts
  src/store/style/getReducer.ts
  src/store/style/landscapeReducer.ts
  src/store/style/markerReducer.ts
  src/store/style/poiReducer.ts
  src/store/style/properties.ts
  src/store/style/reducer.ts
  src/store/style/roadReducer.ts
  src/store/style/transitReducer.ts
  src/store/style/waterReducer.ts
  src/utils/typeCheck.ts
Labels: must, 기능유형
